/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeIdRouteRouteImport } from './routes/$resumeId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeIdIndexRouteImport } from './routes/$resumeId/index'
import { Route as ResumeIdSettingsRouteImport } from './routes/$resumeId/settings'
import { Route as ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125RouteImport } from './routes/$resumeId/sections/{-$sectionKey}.{-$itemId}'

const ResumeIdRouteRoute = ResumeIdRouteRouteImport.update({
  id: '/$resumeId',
  path: '/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIdIndexRoute = ResumeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeIdRouteRoute,
} as any)
const ResumeIdSettingsRoute = ResumeIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ResumeIdRouteRoute,
} as any)
const ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route =
  ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125RouteImport.update(
    {
      id: '/sections/{-$sectionKey}/{-$itemId}',
      path: '/sections/{-$sectionKey}/{-$itemId}',
      getParentRoute: () => ResumeIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$resumeId': typeof ResumeIdRouteRouteWithChildren
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId/': typeof ResumeIdIndexRoute
  '/$resumeId/sections/{-$sectionKey}/{-$itemId}': typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId': typeof ResumeIdIndexRoute
  '/$resumeId/sections/{-$sectionKey}/{-$itemId}': typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$resumeId': typeof ResumeIdRouteRouteWithChildren
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId/': typeof ResumeIdIndexRoute
  '/$resumeId/sections/{-$sectionKey}/{-$itemId}': typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$resumeId'
    | '/$resumeId/settings'
    | '/$resumeId/'
    | '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$resumeId/settings'
    | '/$resumeId'
    | '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
  id:
    | '__root__'
    | '/'
    | '/$resumeId'
    | '/$resumeId/settings'
    | '/$resumeId/'
    | '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeIdRouteRoute: typeof ResumeIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$resumeId': {
      id: '/$resumeId'
      path: '/$resumeId'
      fullPath: '/$resumeId'
      preLoaderRoute: typeof ResumeIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$resumeId/': {
      id: '/$resumeId/'
      path: '/'
      fullPath: '/$resumeId/'
      preLoaderRoute: typeof ResumeIdIndexRouteImport
      parentRoute: typeof ResumeIdRouteRoute
    }
    '/$resumeId/settings': {
      id: '/$resumeId/settings'
      path: '/settings'
      fullPath: '/$resumeId/settings'
      preLoaderRoute: typeof ResumeIdSettingsRouteImport
      parentRoute: typeof ResumeIdRouteRoute
    }
    '/$resumeId/sections/{-$sectionKey}/{-$itemId}': {
      id: '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
      path: '/sections/{-$sectionKey}/{-$itemId}'
      fullPath: '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
      preLoaderRoute: typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125RouteImport
      parentRoute: typeof ResumeIdRouteRoute
    }
  }
}

interface ResumeIdRouteRouteChildren {
  ResumeIdSettingsRoute: typeof ResumeIdSettingsRoute
  ResumeIdIndexRoute: typeof ResumeIdIndexRoute
  ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route: typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}

const ResumeIdRouteRouteChildren: ResumeIdRouteRouteChildren = {
  ResumeIdSettingsRoute: ResumeIdSettingsRoute,
  ResumeIdIndexRoute: ResumeIdIndexRoute,
  ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route:
    ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route,
}

const ResumeIdRouteRouteWithChildren = ResumeIdRouteRoute._addFileChildren(
  ResumeIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeIdRouteRoute: ResumeIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
