/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeIdRouteImport } from './routes/$resumeId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeIdIndexRouteImport } from './routes/$resumeId.index'
import { Route as ResumeIdSettingsRouteImport } from './routes/$resumeId.settings'
import { Route as ResumeIdSectionsRouteImport } from './routes/$resumeId.sections'

const ResumeIdRoute = ResumeIdRouteImport.update({
  id: '/$resumeId',
  path: '/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIdIndexRoute = ResumeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeIdRoute,
} as any)
const ResumeIdSettingsRoute = ResumeIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ResumeIdRoute,
} as any)
const ResumeIdSectionsRoute = ResumeIdSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => ResumeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$resumeId': typeof ResumeIdRouteWithChildren
  '/$resumeId/sections': typeof ResumeIdSectionsRoute
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId/': typeof ResumeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$resumeId/sections': typeof ResumeIdSectionsRoute
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId': typeof ResumeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$resumeId': typeof ResumeIdRouteWithChildren
  '/$resumeId/sections': typeof ResumeIdSectionsRoute
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId/': typeof ResumeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$resumeId'
    | '/$resumeId/sections'
    | '/$resumeId/settings'
    | '/$resumeId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$resumeId/sections' | '/$resumeId/settings' | '/$resumeId'
  id:
    | '__root__'
    | '/'
    | '/$resumeId'
    | '/$resumeId/sections'
    | '/$resumeId/settings'
    | '/$resumeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeIdRoute: typeof ResumeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$resumeId': {
      id: '/$resumeId'
      path: '/$resumeId'
      fullPath: '/$resumeId'
      preLoaderRoute: typeof ResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$resumeId/': {
      id: '/$resumeId/'
      path: '/'
      fullPath: '/$resumeId/'
      preLoaderRoute: typeof ResumeIdIndexRouteImport
      parentRoute: typeof ResumeIdRoute
    }
    '/$resumeId/settings': {
      id: '/$resumeId/settings'
      path: '/settings'
      fullPath: '/$resumeId/settings'
      preLoaderRoute: typeof ResumeIdSettingsRouteImport
      parentRoute: typeof ResumeIdRoute
    }
    '/$resumeId/sections': {
      id: '/$resumeId/sections'
      path: '/sections'
      fullPath: '/$resumeId/sections'
      preLoaderRoute: typeof ResumeIdSectionsRouteImport
      parentRoute: typeof ResumeIdRoute
    }
  }
}

interface ResumeIdRouteChildren {
  ResumeIdSectionsRoute: typeof ResumeIdSectionsRoute
  ResumeIdSettingsRoute: typeof ResumeIdSettingsRoute
  ResumeIdIndexRoute: typeof ResumeIdIndexRoute
}

const ResumeIdRouteChildren: ResumeIdRouteChildren = {
  ResumeIdSectionsRoute: ResumeIdSectionsRoute,
  ResumeIdSettingsRoute: ResumeIdSettingsRoute,
  ResumeIdIndexRoute: ResumeIdIndexRoute,
}

const ResumeIdRouteWithChildren = ResumeIdRoute._addFileChildren(
  ResumeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeIdRoute: ResumeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
