/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeIdRouteImport } from './routes/$resumeId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeIdIndexRouteImport } from './routes/$resumeId.index'
import { Route as ResumeIdSettingsRouteImport } from './routes/$resumeId.settings'
import { Route as ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125RouteImport } from './routes/$resumeId.sections.{-$sectionKey}.{-$itemId}'

const ResumeIdRoute = ResumeIdRouteImport.update({
  id: '/$resumeId',
  path: '/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeIdIndexRoute = ResumeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResumeIdRoute,
} as any)
const ResumeIdSettingsRoute = ResumeIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ResumeIdRoute,
} as any)
const ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route =
  ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125RouteImport.update(
    {
      id: '/sections/{-$sectionKey}/{-$itemId}',
      path: '/sections/{-$sectionKey}/{-$itemId}',
      getParentRoute: () => ResumeIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$resumeId': typeof ResumeIdRouteWithChildren
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId/': typeof ResumeIdIndexRoute
  '/$resumeId/sections/{-$sectionKey}/{-$itemId}': typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId': typeof ResumeIdIndexRoute
  '/$resumeId/sections/{-$sectionKey}/{-$itemId}': typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$resumeId': typeof ResumeIdRouteWithChildren
  '/$resumeId/settings': typeof ResumeIdSettingsRoute
  '/$resumeId/': typeof ResumeIdIndexRoute
  '/$resumeId/sections/{-$sectionKey}/{-$itemId}': typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$resumeId'
    | '/$resumeId/settings'
    | '/$resumeId/'
    | '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$resumeId/settings'
    | '/$resumeId'
    | '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
  id:
    | '__root__'
    | '/'
    | '/$resumeId'
    | '/$resumeId/settings'
    | '/$resumeId/'
    | '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeIdRoute: typeof ResumeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$resumeId': {
      id: '/$resumeId'
      path: '/$resumeId'
      fullPath: '/$resumeId'
      preLoaderRoute: typeof ResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$resumeId/': {
      id: '/$resumeId/'
      path: '/'
      fullPath: '/$resumeId/'
      preLoaderRoute: typeof ResumeIdIndexRouteImport
      parentRoute: typeof ResumeIdRoute
    }
    '/$resumeId/settings': {
      id: '/$resumeId/settings'
      path: '/settings'
      fullPath: '/$resumeId/settings'
      preLoaderRoute: typeof ResumeIdSettingsRouteImport
      parentRoute: typeof ResumeIdRoute
    }
    '/$resumeId/sections/{-$sectionKey}/{-$itemId}': {
      id: '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
      path: '/sections/{-$sectionKey}/{-$itemId}'
      fullPath: '/$resumeId/sections/{-$sectionKey}/{-$itemId}'
      preLoaderRoute: typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125RouteImport
      parentRoute: typeof ResumeIdRoute
    }
  }
}

interface ResumeIdRouteChildren {
  ResumeIdSettingsRoute: typeof ResumeIdSettingsRoute
  ResumeIdIndexRoute: typeof ResumeIdIndexRoute
  ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route: typeof ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route
}

const ResumeIdRouteChildren: ResumeIdRouteChildren = {
  ResumeIdSettingsRoute: ResumeIdSettingsRoute,
  ResumeIdIndexRoute: ResumeIdIndexRoute,
  ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route:
    ResumeIdSectionsChar123SectionKeyChar125Char123ItemIdChar125Route,
}

const ResumeIdRouteWithChildren = ResumeIdRoute._addFileChildren(
  ResumeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeIdRoute: ResumeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
